# -----------------------------
# Genome References
# -----------------------------
reference: "/PATH/TO/HUMAN_GENOME/hg38.fa"
sonic: "/PATH/TO/HUMAN_GENOME/GRCh38.sonic"     # Required for Tardis - Standalone SONIC builder example can be found at:https://github.com/calkan/sonic/tree/f5b20147cacc2cada0ea8042f2aa84a1a99acd98
human_ref_dict: "/PATH/TO/HUMAN_GENOME/hg38.dict"

# -----------------------------
# Truth VCF
# -----------------------------
truth: "/PATH/TO/DATA_DIR/merged_hg38.svs.sort.oa.vcf.gz"

# -----------------------------
# Input & Output Directories
# -----------------------------
sample_path: "/PATH/TO/DATA_DIR/pedigree-dataset"      # directory containing [ID].bam
output: "/PATH/TO/RESULTS_DIR/pedigree-results"        # where results will be written
dragen_dir: "/PATH/TO/RESULTS_DIR/pedigree-results/dragen"

# -----------------------------
# Tool Settings
# -----------------------------
svtypes: ["DEL","INS","INV"]

samples: ["NA12879", "NA12881", "NA12882", "NA12878"]

# List of SV callers to run
callers: [
    "wham",
    "lumpy",
    "dysgu",
    "octopus",
    "smoove",
    "tardis",
    "manta",
    "svaba",
    "cnvpytor",
    "delly",
    "tiddit",
    "gridss",
    "popdel",
    "dragen",
] 


# Truvari benchmarking configurations
truvari_runs:
  type-ignored: "--pctseq 0 --typeignore --passonly"
  type-ignored_fail-included: "--pctseq 0 --typeignore"
  type-included: "--pctseq 0"


