## environments
# python
anaconda3_version: 4.4.0 # some tools originally had 2024.02, not sure which to use
anaconda2_version: 4.4.0 # some tools originally had 2024.02, not sure which to use
tensorflow_version: 2.3.0 

perl_version: 5.24.0
java_version: 1.8.0 
gcc_version: 12.1.0  
R_version: 4.4.0 

## larger tools
bcftools_version: "1.20" 
samtools_version: "1.9"
picard-tools_version: "2.6.0"
gsort_version: "0.1.4" 
htslib_version: "1.14"

## callers
cnvpytor_version: 1.3.1 
cnvnator_version: 0.4.1
delly_version: 1.1.3
gatk_version: 4.2.6.1
gridss_version: 2.13.2 
dysgu_version: 1.6.2 
octopus_version: 0.7.4 
smoove_version: 0.2.8 
sniffles_version: 2.3.3 
svaba_version: 1.2.0
tardis_version: 1.0.7 
tiddit_version: 3.6.1 
manta_version: 1.6.0
wham_version: 1.8.0 
popdel_version: 1.5.0  

# lumpy helpers 
lumpy_version: 0.3.1 
sambamba_version: 0.8.0 
samblaster_version: 0.1.26  

## truvari 
MAFFT_version: 7.505-GCC-11.3.0-with-extensions # for truvari refine   
truvari_version: 4.2.2

## other helpers  
apache-arrow_version: 11.0.0_CPP 
openssl_version: 1.1.1b # for R 
root_version: 6.06.06 
yeppp_version: 1.0.0 
intel_version: perflibs 
